version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_cats
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CATS_Cluster
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data: